version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/usr/src/app
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - "SYS_PTRACE" # Allow ptrace debugging